# Generated by Django 5.2.7 on 2025-11-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
