# Generated by Django 5.2.7 on 2025-11-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_like_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=(2025, 11, 2, 23, 3, 27, 6, 306, 0)),
        ),
    ]
