# Generated by Django 5.2.7 on 2025-11-14 20:27

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.customuser', verbose_name='автор вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(default='static/img/avatar.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(max_length=50, unique=django.db.models.constraints.UniqueConstraint),
        ),
    ]
