# Generated by Django 5.2.7 on 2025-11-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default='time.struct_time(tm_year=2025, tm_mon=11, tm_mday=2, tm_hour=23, tm_min=3, tm_sec=44, tm_wday=6, tm_yday=306, tm_isdst=0)'),
        ),
    ]
