# Generated by Django 5.2.7 on 2025-11-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='Name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название тега'),
        ),
    ]
