# Generated by Django 5.2.7 on 2025-11-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='question_id',
            new_name='question',
        ),
    ]
