# Generated by Django 5.2.7 on 2025-11-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_answer_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Количество лайков'),
        ),
    ]
