# Generated by Django 5.2.7 on 2025-11-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.CharField(),
        ),
    ]
