# Generated by Django 5.2.7 on 2025-11-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_question_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
    ]
