# Generated by Django 5.2.7 on 2025-11-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_question_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
    ]
