# Generated by Django 5.2.7 on 2025-11-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_question_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='question_id',
            field=models.ForeignKey(default=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.CASCADE, to='app.question'),
        ),
    ]
