# Generated by Django 5.2.7 on 2025-11-03 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_like_quantity_like_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question'),
        ),
    ]
