# Generated by Django 5.2.7 on 2025-11-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_like_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='quantity',
            field=models.BigIntegerField(),
        ),
    ]
