# Generated by Django 5.2.7 on 2025-11-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_like_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
