# Generated by Django 5.2.7 on 2025-11-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_answer_id_alter_like_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='question_id',
        ),
    ]
