# Generated by Django 5.2.7 on 2025-11-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_like_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='question_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.question'),
            preserve_default=False,
        ),
    ]
